import Head from 'next/head' 
import styles from '../styles/Home.module.css' 

export default function Home({data}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {
          data.map((item) => (
            <li key={item.id}>
              <a href={item.url}>{item.url}</a>
              <img src={item.url} width='100' height='100'></img>
            </li>
          ))
        }  
        <button>Clica aqui</button>
      </ul>
     
    </div>
  )
}

export const getServerSideProps = async (ctx)=>{

  const res = await fetch('http://localhost:3000/api/dashboard',{
    method:'GET',
    headers:{
      "authorisation":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWZlNTMxYTI0M2I2YWU4YmQ5NzMyMCIsImlhdCI6MTYzOTI2NDE3NywiZXhwIjoxNjM5Mjc0MTc3fQ.TZQSF_SyyC552v4qNLcA5sDjOYxD3fiV0oK7pbSGAE0"
    }
  })
  const resJson = await res.json();

  return {
    props:{
      data:resJson
    }
  }
}
